name: Docker Image CI

on:
  push:
    branches: [ "devops-docker" ]
  pull_request:
    branches: [ "devops-docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the sample fastapi application Docker image
      run: docker build . --file Dockerfile --tag fastapi-sample:$(date +%s)
